apiVersion: v1
kind: Service
metadata:
  name: schedule
  namespace: service-platform
spec:
  selector:
    app.kubernetes.io/name: schedule
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: schedule-hpa
  namespace: service-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: schedule-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-deployment
  namespace: service-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: schedule
  template:
    metadata:
      labels:
        app.kubernetes.io/name: schedule
    spec:
      containers:
      - name: schedule-container
        image: mapzip/schedule-service:latest
        ports:
        - protocol: TCP
          containerPort: 9090
        
        # Config Server 연동을 위한 환경변수
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: "http://config.service-platform.svc.cluster.local:8888"
        - name: SPRING_APPLICATION_NAME
          value: "schedule"
        
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        
        # gRPC Health Check
        livenessProbe:
          grpc:
            port: 9090
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          grpc:
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          successThreshold: 1
---
# HTTP → gRPC 변환을 위한 VirtualService
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: schedule-vs
  namespace: service-platform
spec:
  hosts:
  - "api.mapzip.shop"
  gateways:
  - spring-gateway-gateway
  http:
  - match:
    - uri:
        prefix: "/v1/schedules"
    route:
    - destination:
        host: schedule.service-platform.svc.cluster.local
        port:
          number: 9090
    retries:
      attempts: 3
      perTryTimeout: 10s